
  create table "public"."contact" (
    "id" bigint generated by default as identity not null,
    "name_surname" text not null,
    "phone_number" text not null,
    "email" text not null
      );


alter table "public"."contact" enable row level security;


  create table "public"."custom_content" (
    "id" bigint generated by default as identity not null,
    "header" text not null,
    "paragraph" text not null,
    "image_url" text not null,
    "image_name" text not null
      );


alter table "public"."custom_content" enable row level security;


  create table "public"."lessons" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text not null,
    "price" numeric not null,
    "duration" text not null,
    "isActive" boolean not null
      );


alter table "public"."lessons" enable row level security;


  create table "public"."social_media" (
    "id" bigint generated by default as identity not null,
    "platform" text not null,
    "username" text,
    "link" text
      );


alter table "public"."social_media" enable row level security;

CREATE UNIQUE INDEX contact_pkey ON public.contact USING btree (id);

CREATE UNIQUE INDEX custom_content_pkey ON public.custom_content USING btree (id);

CREATE UNIQUE INDEX lessons_pkey ON public.lessons USING btree (id);

CREATE UNIQUE INDEX social_media_pkey ON public.social_media USING btree (id);

alter table "public"."contact" add constraint "contact_pkey" PRIMARY KEY using index "contact_pkey";

alter table "public"."custom_content" add constraint "custom_content_pkey" PRIMARY KEY using index "custom_content_pkey";

alter table "public"."lessons" add constraint "lessons_pkey" PRIMARY KEY using index "lessons_pkey";

alter table "public"."social_media" add constraint "social_media_pkey" PRIMARY KEY using index "social_media_pkey";

grant delete on table "public"."contact" to "anon";

grant insert on table "public"."contact" to "anon";

grant references on table "public"."contact" to "anon";

grant select on table "public"."contact" to "anon";

grant trigger on table "public"."contact" to "anon";

grant truncate on table "public"."contact" to "anon";

grant update on table "public"."contact" to "anon";

grant delete on table "public"."contact" to "authenticated";

grant insert on table "public"."contact" to "authenticated";

grant references on table "public"."contact" to "authenticated";

grant select on table "public"."contact" to "authenticated";

grant trigger on table "public"."contact" to "authenticated";

grant truncate on table "public"."contact" to "authenticated";

grant update on table "public"."contact" to "authenticated";

grant delete on table "public"."contact" to "service_role";

grant insert on table "public"."contact" to "service_role";

grant references on table "public"."contact" to "service_role";

grant select on table "public"."contact" to "service_role";

grant trigger on table "public"."contact" to "service_role";

grant truncate on table "public"."contact" to "service_role";

grant update on table "public"."contact" to "service_role";

grant delete on table "public"."custom_content" to "anon";

grant insert on table "public"."custom_content" to "anon";

grant references on table "public"."custom_content" to "anon";

grant select on table "public"."custom_content" to "anon";

grant trigger on table "public"."custom_content" to "anon";

grant truncate on table "public"."custom_content" to "anon";

grant update on table "public"."custom_content" to "anon";

grant delete on table "public"."custom_content" to "authenticated";

grant insert on table "public"."custom_content" to "authenticated";

grant references on table "public"."custom_content" to "authenticated";

grant select on table "public"."custom_content" to "authenticated";

grant trigger on table "public"."custom_content" to "authenticated";

grant truncate on table "public"."custom_content" to "authenticated";

grant update on table "public"."custom_content" to "authenticated";

grant delete on table "public"."custom_content" to "service_role";

grant insert on table "public"."custom_content" to "service_role";

grant references on table "public"."custom_content" to "service_role";

grant select on table "public"."custom_content" to "service_role";

grant trigger on table "public"."custom_content" to "service_role";

grant truncate on table "public"."custom_content" to "service_role";

grant update on table "public"."custom_content" to "service_role";

grant delete on table "public"."lessons" to "anon";

grant insert on table "public"."lessons" to "anon";

grant references on table "public"."lessons" to "anon";

grant select on table "public"."lessons" to "anon";

grant trigger on table "public"."lessons" to "anon";

grant truncate on table "public"."lessons" to "anon";

grant update on table "public"."lessons" to "anon";

grant delete on table "public"."lessons" to "authenticated";

grant insert on table "public"."lessons" to "authenticated";

grant references on table "public"."lessons" to "authenticated";

grant select on table "public"."lessons" to "authenticated";

grant trigger on table "public"."lessons" to "authenticated";

grant truncate on table "public"."lessons" to "authenticated";

grant update on table "public"."lessons" to "authenticated";

grant delete on table "public"."lessons" to "service_role";

grant insert on table "public"."lessons" to "service_role";

grant references on table "public"."lessons" to "service_role";

grant select on table "public"."lessons" to "service_role";

grant trigger on table "public"."lessons" to "service_role";

grant truncate on table "public"."lessons" to "service_role";

grant update on table "public"."lessons" to "service_role";

grant delete on table "public"."social_media" to "anon";

grant insert on table "public"."social_media" to "anon";

grant references on table "public"."social_media" to "anon";

grant select on table "public"."social_media" to "anon";

grant trigger on table "public"."social_media" to "anon";

grant truncate on table "public"."social_media" to "anon";

grant update on table "public"."social_media" to "anon";

grant delete on table "public"."social_media" to "authenticated";

grant insert on table "public"."social_media" to "authenticated";

grant references on table "public"."social_media" to "authenticated";

grant select on table "public"."social_media" to "authenticated";

grant trigger on table "public"."social_media" to "authenticated";

grant truncate on table "public"."social_media" to "authenticated";

grant update on table "public"."social_media" to "authenticated";

grant delete on table "public"."social_media" to "service_role";

grant insert on table "public"."social_media" to "service_role";

grant references on table "public"."social_media" to "service_role";

grant select on table "public"."social_media" to "service_role";

grant trigger on table "public"."social_media" to "service_role";

grant truncate on table "public"."social_media" to "service_role";

grant update on table "public"."social_media" to "service_role";


  create policy "Enable read access for all users"
  on "public"."contact"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users"
  on "public"."contact"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Enable delete for authenticated users only"
  on "public"."custom_content"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."custom_content"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."custom_content"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."custom_content"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Enable delete for authenticated users only"
  on "public"."lessons"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."lessons"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."lessons"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."lessons"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."social_media"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."social_media"
  as permissive
  for update
  to authenticated
using (true);

INSERT INTO public.social_media (id, platform, username, link)
VALUES 
(1, 'facebook', null, null),
(2, 'instagram', null, null),
(3, 'linkedin', null, null),
(4, 'twitter', null, null),
(5, 'yooutube', null, null);

INSERT INTO public.contact (id, name_surname, phone_number, email)
VALUES
(1, 'Jan Kowalski', '+48 111 222 333', 'jan.kowalski@gmail.com');


